# Generated by Django 5.0.2 on 2024-02-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('company', models.CharField(max_length=80)),
                ('designation', models.CharField(max_length=100)),
                ('joined_date', models.DateField()),
                ('photo', models.ImageField(upload_to='photos/employee')),
                ('country', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Employee Data',
                'verbose_name_plural': "Employee Data's",
                'db_table': 'Employee Data',
            },
        ),
    ]
